### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by farshed** [farshed/SoundSpice-mobile#4]
**This thread keeps track of planned features and known issues.**

- [ ]  Metadata/ID3 tag editor
- [ ] Music streaming + downloading from SoundCloud & Youtube
- [ ] Data sync with cloud
- [ ] Support FLAC playback
- [ ] Add an option to settings to eagerly fetch lyrics
- [ ] Add multiple sources for lyrics
- [ ] Sample colours from album art instead of blurred background image
- [ ] Allow selecting multiple tracks to share, delete, or add to playlist
- [ ] Add an option to refresh library (rescan music)
- [ ] Make music scan batched instead of scanning all at once
- [ ] Fix album art cache purge
- [ ] Open lyrics on swipe up instead of clicking through the menu
- [ ] Make album art horizontally swipeable to go to next/previous track
- [ ] Add favourite button to add tracks to the favourites playlist
- [ ] Integrate iTunes/Spotify API to automatically search/add album art [Dependant on no. 1]
- [ ] Add audio equalizer
- [ ] Add a "Sort by" button (Title, Artist, Recently added)
- [ ] Add multiple colour themes
- [ ] Add audio loudness normalization (ReplayGain)
- [ ] Revamp Artist and Album screens UI
- [ ] Make SoundSpice available on F-droid [need help with this]
- [ ] Add sleep timer to schedule playback termination
- [ ] Add an app tour for familiarizing user with the UI
- [ ] Replace text input in "Folders to skip" with a filesystem dialog

**Comment by ijiki16** [comment]
Could you make Doc how to build, that would be really nice. So others could build and help with development.

**Comment by Muhammad-Sarfaraz** [comment]
@ijiki16  Yeah hope so,If @farshed  you just provide us some guideline or any code of conduct how to contribute that will be helpful for all of us.
